# Generated by Django 3.2.7 on 2021-11-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadermodel',
            name='file_size',
            field=models.TextField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
