# Generated by Django 3.2.9 on 2021-11-04 08:28

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_uploadermodel_row_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadermodel',
            name='file_upload',
            field=models.FileField(upload_to='data/', validators=[uploader.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='uploadermodel',
            name='row_count',
            field=models.IntegerField(null=True),
        ),
    ]
