# Generated by Django 3.2.9 on 2021-11-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_auto_20211104_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_code', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('age_group', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=6)),
                ('date_specimen', models.DateField(null=True)),
                ('date_result_release', models.DateField(null=True)),
                ('date_rep_conf', models.DateField(null=True)),
                ('date_died', models.DateField(null=True)),
                ('date_recovered', models.DateField(null=True)),
                ('removal_type', models.CharField(max_length=20, null=True)),
                ('admitted', models.CharField(max_length=20, null=True)),
                ('region_res', models.CharField(max_length=20, null=True)),
                ('prov_res', models.CharField(max_length=20, null=True)),
                ('city_mun_res', models.CharField(max_length=20, null=True)),
                ('city_muni_psgc', models.CharField(max_length=20, null=True)),
                ('barangay_res', models.CharField(max_length=20, null=True)),
                ('barangay_psgc', models.CharField(max_length=20, null=True)),
                ('health_status', models.CharField(max_length=50)),
                ('quarantined', models.CharField(max_length=20, null=True)),
                ('date_onset', models.DateField(null=True)),
                ('pregnant', models.CharField(max_length=20, null=True)),
                ('validation_status', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
