# Generated by Django 3.2.9 on 2021-11-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_alter_coviddata_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='age',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='age_group',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='sex',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
